FROM python:3.10-slim-buster

ENV DBT_PROFILES_DIR=/usr/app/profiles

WORKDIR /usr

COPY  . .
COPY profiles /usr/app/profiles


RUN pip install --upgrade pip 
RUN pip install dbt-duckdb 

# ENTRYPOINT [ "/app/dbt_petroleum_analytics" ]

RUN dbt deps 

# CMD ["dbt", "deps"]

# CMD ["python3", "python_scripts/export_reports.py"]