FROM python:3.10-slim-buster

ENV DBT_PROFILES_DIR=/usr/app/profiles

WORKDIR /usr

COPY  . .

COPY profiles /usr/app/profiles

RUN pip install --upgrade pip 
RUN pip install dbt-duckdb 
RUN dbt deps 