dbt_petroleum_analytics:
  outputs:
    prod:
      extensions:
      - httpfs
      - parquet
      secrets:
        - type: s3
          region: us-east-2
          key_id: "{{ env_var('ACCESS_KEY') }}"
          secret: "{{ env_var('SECRET_KEY') }}"
      type: duckdb
      path: prod.duckdb
      threads: 4
  target: prod